/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../model/models';
import { RefreshTokenRequest } from '../model/models';
import { TokenPair } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Perfil del usuario autenticado
     * 
     */
    getCurrentUser(extraHttpRequestParams?: any): Observable<User>;

    /**
     * Iniciar sesión y obtener tokens
     * 
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<TokenPair>;

    /**
     * Cerrar sesión y revocar la familia de refresh tokens
     * Revoca en el servidor la familia completa de refresh tokens de la sesión. Siempre responde 204: no revela si el token era válido, y un logout \&quot;fallido\&quot; no le sirve de nada a un atacante (revocar es inocuo). Sin esto, \&quot;cerrar sesión\&quot; solo borraría tokens del cliente y la familia seguiría viva hasta su TTL. 
     * @param refreshTokenRequest 
     */
    logout(refreshTokenRequest: RefreshTokenRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Renovar el access token con un refresh token
     * 
     * @param refreshTokenRequest 
     */
    refreshToken(refreshTokenRequest: RefreshTokenRequest, extraHttpRequestParams?: any): Observable<TokenPair>;

}
