/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuditEntry } from '../model/models';
import { DashboardMetrics } from '../model/models';
import { TransitionAction } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MetricsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Métricas agregadas del dashboard
     * Todas las métricas en UNA sola pasada con un aggregation pipeline &#x60;$facet&#x60; (no cinco queries). El resultado se cachea en Redis con TTL corto: el segundo request dentro de la ventana se sirve del cache. 
     */
    getDashboardMetrics(extraHttpRequestParams?: any): Observable<DashboardMetrics>;

    /**
     * Acciones del usuario en sesión (sobre la auditoría)
     * Historial de transiciones ejecutadas por el usuario autenticado, leído del log de auditoría (no de &#x60;reviewedBy&#x60;, que solo guarda el último actor). Responde la pregunta \&quot;¿qué envié a revisión / aprobé / rechacé?\&quot; de forma estable aunque otro supervisor haya actuado después. 
     * @param action Filtrar por un tipo de acción.
     * @param limit 
     */
    getMyActivity(action?: TransitionAction, limit?: number, extraHttpRequestParams?: any): Observable<Array<AuditEntry>>;

}
