/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuditEntry } from '../model/models';
import { Transaction } from '../model/models';
import { TransactionPage } from '../model/models';
import { TransactionStatus } from '../model/models';
import { TransactionType } from '../model/models';
import { TransitionRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TransactionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Detalle de una transacción
     * 
     * @param id Identificador de la transacción.
     */
    getTransaction(id: string, extraHttpRequestParams?: any): Observable<Transaction>;

    /**
     * Historial de auditoría (append-only) de una transacción
     * 
     * @param id Identificador de la transacción.
     */
    getTransactionAudit(id: string, extraHttpRequestParams?: any): Observable<Array<AuditEntry>>;

    /**
     * Listar transacciones (paginación y filtros server-side)
     * Listado paginado en servidor. Todos los filtros se resuelven en la base con índices; el cliente nunca recibe el dataset completo. Soporta paginación por cursor (recomendada a volumen) y ordenamiento. 
     * @param cursor Cursor opaco de paginación (devuelto en &#x60;nextCursor&#x60;). Vacío &#x3D; primera página.
     * @param limit Tamaño de página.
     * @param status Filtrar por uno o varios estados.
     * @param type 
     * @param minAmount 
     * @param maxAmount 
     * @param currency 
     * @param counterparty Búsqueda por contraparte (origen o destino).
     * @param dateFrom 
     * @param dateTo 
     * @param sort Campo y dirección, p. ej. &#x60;-createdAt&#x60; (desc) o &#x60;amount&#x60; (asc).
     */
    listTransactions(cursor?: string, limit?: number, status?: Array<TransactionStatus>, type?: TransactionType, minAmount?: number, maxAmount?: number, currency?: string, counterparty?: string, dateFrom?: string, dateTo?: string, sort?: string, extraHttpRequestParams?: any): Observable<TransactionPage>;

    /**
     * Ejecutar una transición de estado (aprobar, rechazar, revisar, revertir)
     * Punto único de mutación del estado. La transición se valida contra la máquina de estados; se aplica el control maker-checker (quien creó la transacción no puede aprobarla); y es idempotente vía la cabecera &#x60;Idempotency-Key&#x60;: reintentos con la misma clave no re-ejecutan la acción. Requiere rol &#x60;supervisor&#x60;. 
     * @param id Identificador de la transacción.
     * @param idempotencyKey Clave única (UUID) por intento de operación. Reintentos con la misma clave devuelven el resultado original sin re-ejecutar. Protege contra doble click y reintentos de red. 
     * @param transitionRequest 
     */
    transitionTransaction(id: string, idempotencyKey: string, transitionRequest: TransitionRequest, extraHttpRequestParams?: any): Observable<Transaction>;

}
