/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionStatus } from './transactionStatus';
import { TransitionAction } from './transitionAction';


/**
 * Registro inmutable (append-only) de una transición.
 */
export interface AuditEntry { 
    id: string;
    transactionId: string;
    action: TransitionAction;
    fromStatus: TransactionStatus;
    toStatus: TransactionStatus;
    /**
     * Usuario que ejecutó la acción.
     */
    actor: string;
    reason?: string | null;
    at: string;
}
export namespace AuditEntry {
}


