/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonthBucket } from './monthBucket';
import { StatusBucket } from './statusBucket';


/**
 * Métricas agregadas calculadas en una sola pasada ($facet).
 */
export interface DashboardMetrics { 
    byStatus: Array<StatusBucket>;
    byMonth: Array<MonthBucket>;
    totalCount: number;
    /**
     * Aprobadas / (aprobadas + rechazadas). 0 si no hay ninguna.
     */
    approvalRate: number;
    inReview: number;
    generatedAt: string;
}

