/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetailsInner } from './errorDetailsInner';


/**
 * Formato de error uniforme en toda la API.
 */
export interface ModelError { 
    /**
     * Código estable, legible por máquina.
     */
    code: string;
    /**
     * Mensaje legible por humanos.
     */
    message: string;
    /**
     * Detalles por campo (validación).
     */
    details?: Array<ErrorDetailsInner> | null;
}

