/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Rol del usuario para RBAC.
 */
export type Role = 'operador' | 'supervisor' | 'auditor';

export const Role = {

    Operador: 'operador' as Role,

    Supervisor: 'supervisor' as Role,

    Auditor: 'auditor' as Role
};

