/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionStatus } from './transactionStatus';


export interface StatusBucket { 
    status: TransactionStatus;
    count: number;
    totalAmount: number;
}
export namespace StatusBucket {
}


