/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionPagePageInfo { 
    hasNextPage: boolean;
    /**
     * Cursor para la siguiente página; null si es la última.
     */
    nextCursor?: string | null;
    /**
     * Conteo aproximado (evita un count costoso exacto a volumen).
     */
    totalEstimate?: number | null;
}

