/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Acción de transición solicitada.
 */
export type TransitionAction = 'APROBAR' | 'RECHAZAR' | 'ENVIAR_A_REVISION' | 'REVERTIR';

export const TransitionAction = {

    Aprobar: 'APROBAR' as TransitionAction,

    Rechazar: 'RECHAZAR' as TransitionAction,

    EnviarARevision: 'ENVIAR_A_REVISION' as TransitionAction,

    Revertir: 'REVERTIR' as TransitionAction
};

