/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionType } from './transactionType';
import { Party } from './party';
import { TransactionStatus } from './transactionStatus';


export interface Transaction { 
    id: string;
    amount: number;
    currency: string;
    type: TransactionType;
    status: TransactionStatus;
    /**
     * Versión del documento para bloqueo optimista; se incrementa en cada transición. El cliente debe enviarla como `expectedVersion` al mutar. 
     */
    version: number;
    source: Party;
    destination: Party;
    /**
     * Glosa o referencia libre.
     */
    reference?: string | null;
    /**
     * Usuario que inició la transacción (maker).
     */
    createdBy: string;
    /**
     * Usuario que ejecutó la última transición (checker).
     */
    reviewedBy?: string | null;
    createdAt: string;
    updatedAt?: string | null;
    /**
     * Campos extra específicos del dominio.
     */
    metadata?: { [key: string]: any; } | null;
}
export namespace Transaction {
}


