/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransitionAction } from './transitionAction';


export interface TransitionRequest { 
    action: TransitionAction;
    /**
     * Versión esperada de la transacción (bloqueo optimista). Si el documento fue modificado entremedio por otro actor, la API responde 409 STALE_VERSION y el cliente debe recargar y reintentar. 
     */
    expectedVersion: number;
    /**
     * Motivo (obligatorio para RECHAZAR y REVERTIR a nivel de lógica).
     */
    reason?: string | null;
}
export namespace TransitionRequest {
}


