/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionPagePageInfo } from './transactionPagePageInfo';
import { Transaction } from './transaction';


/**
 * Página de resultados con paginación por cursor.
 */
export interface TransactionPage { 
    items: Array<Transaction>;
    pageInfo: TransactionPagePageInfo;
}

