/**
 * Consola de Operaciones Transaccionales API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransactionType = 'TRANSFERENCIA' | 'PAGO' | 'ABONO' | 'REVERSA';

export const TransactionType = {

    Transferencia: 'TRANSFERENCIA' as TransactionType,

    Pago: 'PAGO' as TransactionType,

    Abono: 'ABONO' as TransactionType,

    Reversa: 'REVERSA' as TransactionType
};

